chore!: Normalize repository, dropping node <10.13 support
gulpjs/semver-greatest-satisfied-range pull request #11
Opened 2021-12-11 08:35 UTC by sttk

This PR updates this project:

* Updates dependency versions
* Introduces GitHub Actions
* Adds, changes and deletes some project files

2022-01-10 00:58 UTC, phated requested changes
Just needs to be updated to use the main `sver` package instead of my fork with node 0.10 support.

2022-01-10 00:58 UTC, phated commented on LICENSE
> +Copyright (c) 2015, 2017, 2021 Blaine Bublitz <blaine.bublitz@gmail.com>, Eric Schoffstall <yo@contra.io> and other contributors
```suggestion
Copyright (c) 2015, 2017, 2021 Blaine Bublitz <blaine.bublitz@gmail.com> and Eric Schoffstall <yo@contra.io>
```

2022-01-10 00:58 UTC, phated commented on README.md
> +[range-support]: https://github.com/phated/sver-compat#range-support
This needs to be updated to the official `sver` module. The documentation about "sver-compat" need to be updated to reference the "sver" project.

2022-01-10 00:58 UTC, phated commented on package.json
>      "sver-compat": "^1.5.0"
This needs to use `sver` instead of my fork.

2022-01-15 06:22 UTC, sttk commented
@phated I've modified what you pointed out.

I replaced `sver-compat` to `sver` but a test about prerelease version caused an error. Therefore I changed the 3rd parameter of `SemverRange.match` from `true` to `false`, then the test was passed. I don't know whether this modification is correct.

2022-01-31 02:00 UTC, phated commented
Thank you for identifying that change and telling me. I've thought a lot about this and tested some things locally and I feel that our tests were testing our desired behavior—that a prerelease version is not covered by the final release, since there could be breaking changes.

However, there were bugs in sver-compat that weren't handling this correctly which I found while writing some tests against it. For example, `1.0.1-alpha.1` should also not be satisfied by `^1.0.0` because there might be changes that require a patch release in other packages to be compatible. I've added that test on this branch.

2022-01-31 02:02 UTC, phated approved these changes
Thanks for all your work on this! 🙇

2022-01-31 02:03 UTC, merged